---
title: "API documentation"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{API documentation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8} -->
---

Here you will find the full documentation about how to create and use `tensoRphylo::TensorPhyloInstance` objects.
See the [Modeling Framework](articles/dataformat.html) for details about the a
vailable models, and the [Quickstart Guide](articles/tensoRphylo.html) for a more brief introduction to the program.

# Constructor

Create `TensorPhyloInstances` with the 

# Models and Parameters

## Lineage-specific diversification events

### Speciation events

### Extinction events

### Sampling events

### Destructive-sampling events

## Mass-diversification events

### Mass-speciation events

### Mass-extinction events

### Mass-sampling events

### Mass-destructive-sampling events

## State-change events

### Anagenetic events

### Cladogenetic events

## Root Frequencies

## Conditional probabilities

# Numerical settings

## Multithreading

## Numerical integrators

## Approximator algorithms

## Error Handling

## Debugging
