---
title: "Using tensoRphylo"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{Using tensoRphylo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8} -->
---

```{r setup, echo = FALSE, message=FALSE}
library(tensoRphylo)
```

Welcome to the extended documentation for the `R` package `tensoRphylo`, which is an `R` interface to the `C++` library `TensorPhylo` (note the difference in capitalization).
This library is designed to compute probabilities of trees (and discrete character data) for a general class of state-dependent sampled birth-death models.

`TensorPhylo` is a not a _method_, and this package is not intended for directly fitting models to data.
Rather, `TensorPhylo` is a high-performance implementation of a _likelihood function_; it is up to you (or other package developers!) to implement the machinery to fit models of interest using this likelihood function.
The `tensoRphylo` package uses `Rcpp` to expose functionality from `TensorPhylo` to `R` users.
The purpose of this vignette is to show `R` users how to use `tensoRphylo` in their own `R` code.
It is also possible to use the `TensorPhylo` library itself in `R` packages using `Rcpp`, but that is a topic for another vignette.

# Creating a `tensorphylo` instance

<!-- All interactions with `TensorPhylo` are mediated through `R` objects of class `TensorPhyloInstance`. -->
<!-- We can instantiate such an object like so: -->
<!-- ```{r} -->
<!-- tp <- new(TensorPhyloInstance, dim = 2) -->
<!-- ``` -->
<!-- (Note that we must specify the "dimensionality"---the number of discrete states in the model---of the object when we create it. -->
<!-- Later, we'll see how to create a `TensorPhyloInstance` object directly from a phylogenetic tree and discrete character data, in which case the dimensionality is inferred from the data itself.) -->

<!-- Printing `tp` shows that it is simply a pointer to an internal object. -->
<!-- ```{r} -->
<!-- tp -->
<!-- ``` -->
<!-- The internal object is what we call a "distribution handler": it is primarily responsible for communicating parameter values to the `TensorPhylo` library, and for reporting likelihoods back to the `R` side. -->
<!-- To request a likelihood from the `tp` object, use: -->
<!-- ```{r, error=TRUE} -->
<!-- tp$computeLogLikelihood() -->
<!-- ``` -->
<!-- Oops! We forgot to give the object data to work with! -->
<!-- (You might also wonder what parameters it's computing the likelihood _for_; we'll return to the topic of default parameter values in the following section.) -->

# Specifying parameters
