conditionalProbability <- list(
  TIME=0,
	ROOT_SURVIVAL=1,
	ROOT_MRCA=2,
	ROOT_SAMPLING=3,
	STEM_SURVIVAL=4,
	STEM_ONE_SAMPLE=5,
	STEM_TWO_EXT_SAMPLES=6,
	STEM_TWO_SAMPLES=7,
	ROOT_SAMPLING_AND_MRCA=8
)

approximatorVersion <- list(
  AUTO_TUNING=0,
  SEQUENTIAL_OPTIMIZED=1,
  SEQUENTIAL_BRANCHWISE=2,
  PARALLEL_OPTIMIZED=3,
  PARALLEL_BRANCHWISE=4
)

integrationScheme <- list(
  EULER=0,
  RUNGE_KUTTA4=1,
  RUNGE_KUTTA54=2,
  RUNGE_KUTTA_DOPRI5=3
)

debugMode <- list(
  DBG_NONE=0,
  DBG_PRINT=1,
  DBG_FILE=2
)
